### ISSUE TITLE
ticket anual pode ser comprado sem intermedio da empresa

### ISSUE THREAD

**Issue by mathiasgrimm** [marlonbernardes/awesome-berlin#11]
Eu comprei esse mes o ticket anual, que é pago mensalmente e custa cerca de 60 euros por mes.

Vou adicionar mais detalhes aqui mas acredito que essa informação é crucial uma vez que economizar 20 euros por mes é muita coisa.

**Comment by marlonbernardes** [comment]
Opa, boa. Sim, é uma boa dica... se quiser fazer um PR, sinta-se livre. Acho que vale a pena ter isso no guia...

Valeu!

**Comment by mathiasgrimm** [comment]
sim, vou fazer em breve

**Comment by lucasrenan** [comment]
@mathiasgrimm rola pagar mensalmente? estou querendo comprar pro mes que vem

**Comment by mathiasgrimm** [comment]
sim

**Comment by marceloboeira** [comment]
@mathiasgrimm se for fazer a PR avisa, eu tava pensando em colocar informações sobre o formulário :)

**Comment by wormangel** [comment]
Outra coisa é que dá pra fazer o ticket mensal (na verdade na forma do cartão VBB EcoCard) online, sem precisar de formulario (e com ajuda do google translate haha). Fiz pra minha esposa :)

**Comment by wormangel** [comment]
https://www.abo-antrag.de/

**Comment by marlonbernardes** [comment]
@wormangel qual o preço por mês? Não tem nenhuma diferença em relação ao ticket da BVG né?

**Comment by marlonbernardes** [comment]
@wormangel depois que preenche o formulário online o ticket vem por correio? Vem todo mês um ticket ou chega em "lotes"? Ou é um cartão mesmo?

**Comment by wormangel** [comment]
O ticket da BVG que a gente pega com a empresa na verdade é emitido pela VBB - todos os tickets semanais/mensais de Berlin são, inclusive o da empresa e esse EcoCard que vc faz online. O preço por mês é € 63 - o mesmo preço do nosso, sem o desconto de 3% por ser 'company ticket' e sem o desconto extra de 10 mangos da firma. É exatamente a mesma coisa :D Chega pelo correio o cartão, mas tem uma diferença pro nosso: **não tem número/não é pessoal. A pessoa pode compartilhar com os amigos, família, o que quiser.** A regra de poder levar uma pessoa extra depois das 20h e durante o fim de semana **também vale.** Muito bom!

**Comment by wormangel** [comment]
Ah, e é um cartão tipo um cartão de crédito, vc ja deve ter visto gente no metrô usando. E embora nunca tenha acontecido com minha esposa, já vi com outros randoms: quando fiscal quer olhar esse cartão, ele só faz olhar mesmo (eu pensava que ele ia por naquele leitor mas pelo jeito aquilo é so pra QR code mesmo, ticket online mobile).. e no ônibus é só mostrar mesmo (o caba ignora tanto quanto o ticket normal hahaha)

**Comment by wormangel** [comment]
@lucasrenan pago mensal o meu (mas rola mais desconto se pagar de uma vez)

**Comment by wormangel** [comment]
@marlonbernardes ah ultimo lembrete: vc tem até o dia 10 pra fazer o ticket anual, pra receber o do proximo mes (se nao, recebe so no proximo proximo). O cartão chega pelo correio perto do fim do mês anterior (e.g. se vc fez até o dia 10 ele começa a valer dia 1o do proximo mes e chega na sua casa la pelo dia 28, 29)

**Comment by marlonbernardes** [comment]
@wormangel opa, valeu pelas infos ❤️ . Acabei de me inscrever aqui, logo logo eu coloco no guia como fazer (já fiz um gif com um exemplo):

![sbahn](https://cloud.githubusercontent.com/assets/2975955/21577255/c1620f34-cf54-11e6-9859-ebad96aca928.gif)

**Comment by marlonbernardes** [comment]
@wormangel @marceloboeira @lucasrenan feito! agora tá disponível no guia (em inglês e português):

https://marlonbernardes.github.io/awesome-berlin/pt-br/pages/transporte-publico.html
https://marlonbernardes.github.io/awesome-berlin/en/pages/public-transport.html
