### ISSUE TITLE
Driving license theory test tips

### ISSUE THREAD

**Issue by denisn26** [marlonbernardes/awesome-berlin#114]
There was a link to awesome guide about theory exam questions. It is deleted now due to copyright issues. Can I somewhere find original document or deleted one? Thanks in advance!

https://github.com/marlonbernardes/awesome-berlin/issues/102
https://github.com/marlonbernardes/awesome-berlin/issues/105

**Comment by marlonbernardes** [comment]
Unfortunately I don't think it's available anymore... 
I'll close this issue as there's nothing I can do, sorry!
