### ISSUE TITLE
registro de residência

### ISSUE THREAD

**Issue by bsao** [marlonbernardes/awesome-berlin#13]
Ficou a dúvida!

No caso de casais, que o cônjuge vá depois do pra Berlim:

- O primeiro que chega a berlim deve registrar os dois ( campos 8 e 9) ou somente ele?

Abs

**Comment by marlonbernardes** [comment]
@bsao descobriu a resposta? não passei por isso, infelizmente não sei responder...

**Comment by bsao** [comment]
Estou em contato com uma empresa de Relocation e ja estou chegando em berlin e vou fazer o processo na prática, com isso mando um PR com a real solução :)

**Comment by marlonbernardes** [comment]
@bsao opa, seria ótimo! :) 
Eu acho que descobri a resposta, dá uma olhada no campo 13 do formulário de exemplo do guia:

![image](https://cloud.githubusercontent.com/assets/2975955/21353134/f9ae6402-c6c4-11e6-923a-c2bb8b43f1f7.png)

É isso que você tem que preencher.

**Comment by marlonbernardes** [comment]
Ou seja, registre apenas você (afinal sua esposa ainda não está vivendo em Berlin), e informe o endereço da esposa no campo 13.

Quando ela chegar na cidade você pode atualizar o registro de residência sem problemas para incluir ela.

**Comment by marlonbernardes** [comment]
@bsao eu vou fechar a issue, depois se quiser pode fazer um PR explicando como tu fez!
