### ISSUE TITLE
Ideia - Informações sobre aluguel

### ISSUE THREAD

**Issue by thiagoxvo** [marlonbernardes/awesome-berlin#2]
- Documentos necessários/recomendados
- Caução
- Como contar os cômodos
- Aluguel quente/frio
- Sites de imobiliarias

Deve ter mais coisas que não lembro agora :)

**Comment by marlonbernardes** [comment]
Boa. Vou fazer um guia separado com dicas de como alugar um apartamento.

**Comment by diegoarcega** [comment]
dados interessantes sobre startups London x Berlin 

![9518b63f-3b00-484c-91a6-80d5e232c883-original](https://cloud.githubusercontent.com/assets/1951007/17296418/99707d02-57d7-11e6-8d4f-845318b2beeb.png)

**Comment by rubenspgcavalcante** [comment]
Vou tentar fazer algo sobre esse tópico. 👍
