### ISSUE TITLE
Number26 - não aceitam passaporte BR

### ISSUE THREAD

**Issue by victorisunc** [marlonbernardes/awesome-berlin#3]
Só uma pequena observação, atualmente eles não aceitam passaporte brasileiro para identificação via chat/webcam.

**Comment by rafaelcaricio** [comment]
Confirmo. Tentei e nao rolou. Mas parece que tem outra forma de validar. Mas eu desisti.

**Comment by victorisunc** [comment]
Tem o PostIdent, onde você vai num correio qualquer levando o papel impresso, passaporte e comprovante de residência, mas não sei se eles aceitam o passaporte brasileiro.

**Comment by marlonbernardes** [comment]
Pois é, quando eu fui fazer (umas 3 semanas atrás) também não aceitavam passaporte brasileiro, mas o pessoal do Number26 falou que passariam a aceitar na semana seguinte. Pelo jeito foi mentira :(

Enfim, vou editar o guia. Valeu galera!

**Comment by marlonbernardes** [comment]
@chiurox pra fazer PostIndent eles aceitam passaporte brasileiro. Foi assim que eu abri minha conta. Mas para identificar via vídeo chamada pelo jeito ainda não rola usar o passaporte tupiniquim.

Ajustei o guia. Valeu por reportar @chiurox & @rafaelcaricio!
