### ISSUE TITLE
Informação sobre o Startkarte.

### ISSUE THREAD

**Issue by leonardocardoso** [marlonbernardes/awesome-berlin#36]
O cartão que você poder pegar nas lojas da BVG antes do seu ticket anual chegar na sua casa para já usufruir do benefício. http://www.s-bahn-berlin.de/aboundtickets/startkarte.htm

**Comment by marlonbernardes** [comment]
@LeonardoCardoso @rubenspgcavalcante feito!

**Comment by rubenspgcavalcante** [comment]
Boa @marlonbernardes !!!

**Comment by leonardocardoso** [comment]
Valeu, @marlonbernardes!!!
