### ISSUE TITLE
Informações sobre como trazer seu pet junto para a Alemanha

### ISSUE THREAD

**Issue by acidio** [marlonbernardes/awesome-berlin#41]
Olá pessoal, isso foi algo que acabei passando antes de vir pra cá, foi bem chato no início pra achar as infos e principalmente para entender os prazos e confirmar nos orgãos competentes.

Acham válido um tópico a esse respeito? Se sim, posso contribuir com isso.

**Comment by ehkenne** [comment]
Já comecei a escrever sobre como foi o meu processo de trazer minha cachorrinha pra cá. Essa semana eu abro um PR :)

**Comment by acidio** [comment]
Legal @ehkenne deixarei para complementar caso precise :)

**Comment by marlonbernardes** [comment]
@acidio a @ehkenne escreveu o guia. Você pode conferir [aqui](https://marlonbernardes.github.io/awesome-berlin/pt-br/pages/trazendo-pet-do-brasil.html) e revisar/adicionar mais informações se quiser. Pull-requests continuam sendo bem vindos! :)

**Comment by acidio** [comment]
@marlonbernardes e @ehkenne o que estou pensando em fazer é checar as diferenças entre a vinda de gatos e cães, o registro e a taxa eu não tenho certeza se tem para gatos, vou verificar. :)
