### ISSUE TITLE
[en] Renting an apartment section

### ISSUE THREAD

**Issue by pedrovitti** [marlonbernardes/awesome-berlin#48]
The english version is not synced with the portuguese and doesn't have the section with information about how to rent an apartment in Berlin (https://marlonbernardes.github.io/awesome-berlin/pt-br/pages/alugando-apartamento.html#alugando-apartamento)

**Comment by marlonbernardes** [comment]
Fixed by @Caroldveiga.

**Comment by pedrovitti** [comment]
Fixed by #70.
