### ISSUE TITLE
Autenticação de cartão diário, semanal e mensal.

### ISSUE THREAD

**Issue by leonardocardoso** [marlonbernardes/awesome-berlin#52]
Amigos meus foram repreendidos pelos fiscais da BVG que informaram que mesmo cartões diários, semanais e mensais devem ser validados nas máquinas mesmo que contenham a data porque a data informa quando foi comprado e a validação é quando ele começa a valer.

**Comment by marlonbernardes** [comment]
Boa, o texto realmente não está claro. Só é necessário validar tickets de longa duração caso eles não tenham a data inicial/final impressa neles. O ticket mensal/semanal flexível não precisa ser validado, já fui parado mais de uma vez por fiscais e nunca tive problemas... 

A próxima vez que eu atualizar o guia eu adiciono essa informação na página de transporte público (PR's também são bem vindos se quiser ajustar essa parte do texto! :) )

Valeu!
