### ISSUE TITLE
Non-https iframe being loaded

### ISSUE THREAD

**Issue by gregdeane** [marlonbernardes/awesome-berlin#55]
On the landing page, there's a non-https iframe being loaded that is blocked by recent version of Chrome / Version 58.0.3029.110 (64-bit).

---

<img width="986" alt="screen shot 2017-05-11 at 07 29 14" src="https://cloud.githubusercontent.com/assets/4949000/25934023/c2d3bef2-361b-11e7-9c3b-df0838afdc12.png">

**Comment by gregdeane** [comment]
This appears to no longer be an issue.

**Comment by marlonbernardes** [comment]
Cool, it was a problem related to disqus. Apparently they fixed it. Thanks for reporting back.
