### ISSUE TITLE
Drivers license page/resources list

### ISSUE THREAD

**Issue by danieladelvos** [marlonbernardes/awesome-berlin#59]
Under the "Berlin.de" resource list the bullet "Umstellung der Fahrerlaubnis" technically refers to changing the old German paper license to the new card style. It appears you want to link to the following URLs which explain how to convert a foreign license to a German one:

- ["Umschreibung einer ausländischen Fahrerlaubnis aus einem EU-/EWR-Staat"](http://www.berlin.de/labo/mobilitaet/fahrerlaubnisse-personen-und-gueterbefoerderung/dienstleistungen/service.213924.php/dienstleistung/121598/) (for EU/EWR-country license holders)
- ["Umschreibung einer ausländischen Fahrerlaubnis aus einem Nicht-EU/EWR-Land (Drittstaat/Anlage 11)"](http://www.berlin.de/labo/mobilitaet/fahrerlaubnisse-personen-und-gueterbefoerderung/dienstleistungen/service.213924.php/dienstleistung/327537/) (for non-EU/EWR-country license holders)

**Comment by marlonbernardes** [comment]
@danieladelvos nice, great catch! I'll fix this shortly, thanks a lot for reporting!
