### ISSUE TITLE
Pré requisitos para o plano de saúde

### ISSUE THREAD

**Issue by csokol** [marlonbernardes/awesome-berlin#6]
Olá! Antes de tudo parabéns e obrigado pelo guia, é muito bom!

Uma dúvida sobre o plano de saúde público. Nos pré requisitos tem um link para a seção sobre o plano de saúde:

![image](https://cloud.githubusercontent.com/assets/1001742/17516844/180ba2a8-5e41-11e6-88b0-50fda82eb8d6.png)

Mas na seção sobre o plano de saúde não tem os pré requisitos :-)

Quais seriam? Ter feito o registro de residência é o suficiente?

**Comment by marlonbernardes** [comment]
@csokol Opa! Valeu mesmo!

Quanto ao guia: vou editar para deixar ele mais claro. 
**EDIT**: Adicionei uma pequena explicação em a2bc390

Na verdade eu não posso citar os pré-requisitos, pois imagino que cada associação (ex.: TK, AOK, etc), deve ter requerimentos diferentes.

De qualquer forma, o que eu precisei enviar para a TK para conseguir o meu seguro de saúde:
- Preencher e enviar um formulário com os meus dados (eles me enviaram o formulário por email)
- Preencher e enviar um formulário (Non-Contributory Dependants Co-Insurance) com as informações da minha esposa (não contribuinte na época)
- Enviar scan da minha foto biométrica (eles precisam da foto para imprimir na carteirinha)
- Enviar scan da certidão de casamento + scan da tradução juramentada

Basicamente consegui fazer todo o processo por email. Conheço algumas pessoas que precisaram enviar as fotos por correio, pois se a qualidade delas não for boa (ex.: ao invés de escanear, tirar foto da foto com o celular), eles não vão aceitar.

Ah, por último: eu **não** precisei enviar para eles uma cópia do meu registro de residência, eles não solicitaram.

**Comment by marlonbernardes** [comment]
![image](https://cloud.githubusercontent.com/assets/2975955/17556079/63dad04c-5f12-11e6-8ffb-6882a64ca625.png)
