### ISSUE TITLE
[pt-br] Question. Carta da pessoa que está te hospedando

### ISSUE THREAD

**Issue by fernandosouza** [marlonbernardes/awesome-berlin#71]
Não sei se esse é a melhor forma para postar dúvidas. Mas lá vai:

Como seria essa cart? Quais as informações que devem ter ela? Se eu alugar um apartamento no Airbnb o proprietário pode disponibilizar essa carta para mim?

**Comment by marlonbernardes** [comment]
Infelizmente eu não tenho um template da carta, mas deve ser fácil conseguir um: simplesmente peça para o proprietário do AirBnb a carta para fazer o Anmeldung que ele deve te fornecer uma...

**Comment by fernandosouza** [comment]
Valeu Marlon. Não sabia que dava para fazer com apartamentos pelo Airbnb.

**Comment by marlonbernardes** [comment]
Na verdade depende, o ideal é conversar com a(o) proprietária(o) antes pra saber se pode... normalmente quando se aluga um apartamento para vários meses, eles já esperam que o locatário solicite essa carta. Bom, de qualquer forma é bom perguntar antes...
