### ISSUE TITLE
Add Information about Meldebescheinigung? And also the difference between anmeldung and Meldebescheinigung?

### ISSUE THREAD

**Issue by ChikkannaSuhas** [marlonbernardes/awesome-berlin#78]

**Comment by nicbou** [comment]
The Meldebescheinigung is the piece of paper you get when doing the Anmeldung. The Anmeldung is the process, and the Meldebescheinigung is the result.

**Comment by marlonbernardes** [comment]
Thanks for clarifying it, @nicbou! Your contributions are always helpful and much appreciated!
